import { loader } from "fumadocs-core/source";
// Generated by fumadocs-mdx (createMDX in next.config / the `fumadocs-mdx`
// postinstall). Lives at the frontend root, outside src/, so it's a relative
// import rather than the "@/" alias.
import { docs } from "../../.source/server";

export const source = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
});
